// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UredivanjeKategorijaIPodkategorijaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void uredivanjeKategorijaIPodkategorija() {
    driver.get("http://localhost:3000/login");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("admin");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("pass");
    driver.findElement(By.cssSelector(".tamniji")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(2) .MuiCardMedia-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Moj profil")).click();
    driver.findElement(By.cssSelector("a:nth-child(4) > .gumbic")).click();
    driver.findElement(By.id("imeKategorije")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("imeKategorije")).sendKeys("alati");
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("imePodKategorije")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiFormGroup-root:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiFormGroup-root:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiFormGroup-root:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiFormGroup-root:nth-child(2) .MuiListItem-root:nth-child(6) .PrivateSwitchBase-input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("imePodKategorije")).sendKeys("mac");
    driver.findElement(By.cssSelector(".MuiFormGroup-root:nth-child(2) .MuiListItem-root:nth-child(6) .PrivateSwitchBase-input")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiFormGroup-root:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiFormGroup-root:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiFormGroup-root:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".MuiFormGroup-root:nth-child(3) .MuiListItem-root:nth-child(5) .PrivateSwitchBase-input")).click();
    driver.findElement(By.id(":r9:")).click();
    driver.findElement(By.id(":r9:")).sendKeys("2");
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(5)")).click();
  }
}
